### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by russel5** [dosomder/byeselinux#2]
Hello @dosomder can you tell me, where are i'm need defined this
`#ifdef REPLACE_MODULE`
In my z3c your byeselinux use the mhl driver and not loaded original after injecting.
Thanks.

**Comment by dosomder** [comment]
If you want to replace another module, paste this line in the top of the c file
`#define REPLACE_MODULE`
then recompile it

**Comment by russel5** [comment]
Thanks
